export const CHANGE_USER_NAME = "CHANGE_USER_NAME";
export const SEARCH_USER = "SEARCH_USER";
export const RECEIVE_USER_PROFILE = "RECEIVE_USER_PROFILE";
export const RECEIVE_USER_REPOS = "RECEIVE_USER_REPOS";
